services:
    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags: [{ name: doctrine.event_subscriber, connection: default }]

doctrine:
    dbal:
        mapping_types:
            _text: string
        types:
            geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
    orm:
        dql:
            string_functions:
                ST_AsGeoJSON: 'Jsor\Doctrine\PostGIS\Functions\ST_AsGeoJSON'
                ST_GeomFromGeoJSON: 'Jsor\Doctrine\PostGIS\Functions\ST_GeomFromGeoJSON'
            numeric_functions:
                ST_Distance: 'Jsor\Doctrine\PostGIS\Functions\ST_Distance'
                ST_MakePoint: 'Jsor\Doctrine\PostGIS\Functions\ST_MakePoint'