twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig', '@MeteoConceptHCaptcha/hcaptcha_form.html.twig']

when@test:
    twig:
        strict_variables: true
